source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!

target 'STIBottomSheet_Example' do
  pod 'STIBottomSheet', :path => '../'

  target 'STIBottomSheet_Tests' do
    inherit! :search_paths
  end
end
